<?php
/*$fm = $this->flashMessenger()->setNamespace('zfcuseradmin')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}*/
?><table class="table">


    <?php // Table header ?>
    <tr>
    <?php foreach($this->userlistElements as $name => $element):?>
        <th><?php echo $this->escapeHtml($name ?: $element)?></th>
    <?php endforeach?>
    <th>Roles</th>
    <th>Actions</th>
    </tr>

    <?php // Users
    foreach ($this->users as $user):?>
        <tr>
        <?php foreach($this->userlistElements as $element):?>
            <td class='row_<?php echo $element?>'>
                <?php
                    $func = 'get' . ucfirst($element);
                    echo $user->$func()
                ?>
            </td>
        <?php endforeach?>
        <td><?=join(' ', $user->roles())?></td>
        <td>
            <a href='<?php echo $this->url('zfcadmin/zfcuseradmin/access', array('userId' => $user->getId()))?>'>Access</a> |
            <a href='<?php echo $this->url('zfcadmin/zfcuseradmin/edit', array('userId' => $user->getId()))?>'>Edit</a> |
            <a href='<?php echo $this->url('zfcadmin/zfcuseradmin/remove', array('userId' => $user->getId()))?>'>Delete</a>
        </td>
    <?php endforeach ?>
</table>
<?php echo $this->paginationControl($this->users, 'Sliding', 'zfc-user-admin/user-admin/pagination_userlist.phtml'); ?>

<p>
    <a class="" href="<?php echo $this->url('zfcadmin/zfcuseradmin/create');?>">Add new user</a>
</p>
