<div class="row">
    <div class="col-md-1">
        <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
    </div>
    
    <div class="col-md-11">
        <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
        <?php if(!$this->isAllowed('user-interface', 'use')):?>
            <div class="alert alert-warning" role="alert">
                <?php echo $this->translate("zfcuseradmin.account.not_activated");?>
                <form 
                    name='resend_confirmation_mail'  
                    class="form-inline"
                    method="post"
                    action="<?php echo $this->url('zfcuseradmin-confirmation-sent')?>"
                >
                    <button type="submit" class="btn btn-default">
                        <?php echo $this->translate("zfcuseradmin.account.resend_confirmation") ?>
                    </button>
                </form>
            </div>
        <?php endif?>

        <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>

    </div>
</div>


